site_name: My Docs
# [テーマ]
theme:
  name: material
  # ロゴ（Material Designのアイコンを使用）
  logo: material/book-open-page-variant
  # サイトの言語
  language: ja
  # アイコン設定
  icon:
    logo: material/book-open-page-variant
  # アイコンパック
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  font:
    # 通常のフォント
    text: Roboto
    # codeの等幅フォント設定
    code: Roboto Mono
  features:
    # ページナビゲーションを折りたたみ可能なリンクで左側に配置します。
    - navigation.expand
    # トップへ戻るボタン
    - navigation.top
    # スクロールしたときヘッダーを自動的に非表示にする
    - header.autohide
    # 検索の候補リスト表示を表示する
    - search.suggest
    # 検索で一致した結果をハイライトする
    - search.highlight
    # コンテンツタブ表示を有効にする
    - content.tabs.link
  # ダークモードスイッチ
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
# [プラグイン]
plugins:
  # 検索機能
  - search:
      lang: ja
      # インデックス対象の条件
      separator: '[\s\-\.]'
      # 各ページのタイトル、セクション見出し、および全文にインデックスを付けます。
      indexing: 'full'
  # mermaidの表示設定
  # mkdocs-mermaid2-plugin
  - awesome-pages
# [拡張機能]
markdown_extensions:
    # 目次
    - toc:
        # 自動生成を有効にする
        permalink: true
        # 目次の上に表示する文言
        title: 見出し
        # 見出しにする深さ
        toc_depth: 3
    # コードハイライトの設定（デフォルトのcodehiliteを使わずに拡張機能を使用）
    - pymdownx.highlight:
        # (auto_titleなどの他の機能を有効にするためtrue)
        use_pygments: true
        # タイトルが設定されていないと自動的に言語名を表示する
        auto_title: true
        # 行番号を表示する
        linenums: true
        # 行を選択できアンカーリンクを生成可能にする
        anchor_linenums: true
    # コードハイライトの設定(インラインブロック版)
    - pymdownx.inlinehilite
    # アラート修飾(Note修飾)を有効化
    - admonition
    # コンテンツの折りたたみを有効化
    - pymdownx.details
    # 打ち消し線の追加
    - pymdownx.tilde
    # 下付き文字と上付き文字の追加（tilde拡張も必要）
    - pymdownx.caret
    # テキストの強調表示が可能になる（tilde,caret拡張も必要）
    - pymdownx.mark
    # ドキュメント内の追加、削除、または更新されたセクションを強調表示
    - pymdownx.critic
    # キーボードアイコンの追加
    - pymdownx.keys
    # 略語
    - abbr
    # 参照
    - attr_list
    # HTML内にMarkdownを記述できる
    - md_in_html
    # 絵文字とアイコンのサポート
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    # mermaidの表示設定
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
# [カスタムCSS]
extra_css:
  - docs/assets/css/extra.css
# [カスタムJS]
# extra_javascript:
#   - assets/js/extra.js
# [mkdocsの拡張]
extra:
  # このサイトのバージョン
  version: 1.0
  # フッターのソーシャルリンク
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/sample
      name: ryohei_takasugi on Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/t012093
      name: t012093 on Github
# [フッター] 著作権表示
copyright: Copyright &copy; 2024 naoya kusunoki

nav:
  - プロジェクトビジョン: プロジェクトビジョン.md
  - 議事録:
    - 2025年1月7日: meeting/2025_01_meeting.md
  - コミュニティ:
    - 基本情報:
      - 概要: community.md
      - エコシステム: community_ecosystem.md
      - コラボレーション: collaboration.md
      - 貢献ガイドライン: contribution_guidelines.md
    - 参加について:
      - 参加形態: コミュニティー/参加形態について.md
      - コミュニティ行動規範: コミュニティー/コミュニティ行動規範詳細資料.md
    - インセンティブ:
      - インセンティブ制度: コミュニティー/インセンティブ制度.md
      - ベーシックインセンティブ: コミュニティー/ベーシックインセンティブ制度.md
    - コミュニケーション:
      - Discordチャンネル: コミュニティー/discord_channels.md
      - AIイベント招待: コミュニティー/aiイベント招待.md
  - プロジェクト:
    - AR都市開発:
      - AR自然豊かな未来都市: projects/AR自然豊かな未来都市.md
      - AR都市構想プロジェクト: projects/ar_urban_development.md
    - ライフジーニアス: projects/lifegenius.md
  

# ローカル環境で表示する場合はfalse、Webサーバー経由ならTrue
use_directory_urls: false
# 公開するページのPort番号を指定
dev_addr: '0.0.0.0:8000'
