site_name: Lifegenius # プロジェクト名
site_description: 遺伝子とAIが導く、パーソナライズド・ライフデザイン # プロジェクトの簡単な説明
site_author: naoya kusunoki # 開発者名
repo_url: https://github.com/weuse1324/Lifegenius-website # リポジトリURL

nav:
    - ホーム: index.md # ホームページ
    - インストール方法: installation.md # インストール方法
    - 使い方: usage.md # 使い方
    - Lifegenius: lifegenius.md

theme:
    name: material # テーマ名
